#!/bin/bash
#
# finalize-hosts-127-v4.sh
#
# BCM only accepts a single finalizescript per category, so this is now the
# ONE combined finalize script for this category. It merges what used to be
# two separate scripts:
#
#   PART 1 — hosts fix (formerly finalize-hosts-127-v3.sh)
#   PART 2 — LDAP detach / cmsupport preserve / cuda-dcgm disable
#            (formerly finalize-ldap-dcgm-disable-v2.sh)
#
# Each part is independent and idempotent - a failure or skip in one does not
# block the other. set -u only (no -e), same as both source scripts, so one
# part's early-exit-on-missing-file doesn't kill the rest of the script.
#
# ============================================================================
# PART 1 — hosts fix
# ============================================================================
#
# Supersedes v1 (build log §8.9) and complements v2's systemd self-heal.
#
# v4 (2026-09-29): no functional change from v3 - confirmed working on a
# real boot (rack08node18): the appended 127.0.1.1 line survives past
# cmd's "BEGIN/END AUTOGENERATED SECTION" rewrite, landing correctly after
# END AUTOGENERATED SECTION as a separate, untouched line:
#   root@rack08node18:~# cat /etc/hosts
#   # BEGIN AUTOGENERATED SECTION -- DO NOT REMOVE
#   ...
#   # END AUTOGENERATED SECTION   -- DO NOT REMOVE
#   127.0.1.1   rack08node18
#
# ROOT CAUSE CONFIRMED (2026-09-02): per BCM's own shipped example script
# (/cm/local/apps/cmd/etc/htdocs/scripts/finalize/log_available_environment_variables.sh),
# "The root / of the running node is always mounted on /localdisk" during
# the finalize stage. v1 wrote to /etc/hosts, which at that point in the
# node-installer sequence is the ramdisk's own throwaway /etc/hosts, not
# the target node's persisted file - which is why the append never
# survived, confirmed directly in node-installer logs (the script ran and
# reported success, but the appended line was never present after boot).
#
# This version writes to /localdisk/etc/hosts instead - the correct path
# for the file that actually gets carried onto the booted node.
#
# Note: $CMD_HOSTNAME (if it exists - not yet confirmed against a real
# `env | grep CMD_` dump from this cluster) is tried first since it would
# be more directly authoritative than the ramdisk's own `hostname` output;
# falls back to `hostname` either way, matching v1's original behavior.
#
# Idempotent: safe to run again on a reinstall without duplicating the entry.

set -uo pipefail

HOSTS_FILE="/localdisk/etc/hosts"
NODE_HOSTNAME="${CMD_HOSTNAME:-$(hostname -s 2>/dev/null || hostname 2>/dev/null || echo unknown-host)}"

log_hosts() { echo "finalize-hosts-127-v4[${NODE_HOSTNAME}]: $*"; }

if [[ -z "$NODE_HOSTNAME" || "$NODE_HOSTNAME" == "unknown-host" ]]; then
  log_hosts "could not determine hostname (checked \$CMD_HOSTNAME and 'hostname') - skipping part 1" >&2
elif [[ ! -f "$HOSTS_FILE" ]]; then
  log_hosts "${HOSTS_FILE} does not exist at this stage - skipping part 1" >&2
elif grep -qE "^127\.0\.1\.1[[:space:]]+${NODE_HOSTNAME}([[:space:]]|\$)" "$HOSTS_FILE" 2>/dev/null; then
  log_hosts "127.0.1.1 ${NODE_HOSTNAME} already present - skipping"
else
  echo "127.0.1.1   ${NODE_HOSTNAME}" >> "$HOSTS_FILE"
  log_hosts "appended 127.0.1.1 ${NODE_HOSTNAME} to ${HOSTS_FILE}"
fi

# ============================================================================
# PART 2 — LDAP detach / cmsupport preserve / cuda-dcgm disable
# ============================================================================
#
# Merges the filesystem-level portion of rack_lifecycle.sh's "handoff" step
# into the node-installer finalize stage, so a production node comes up
# already LDAP-detached, cuda-dcgm-autostart-disabled, and with cmsupport
# preserved as a local account - without a separate post-boot
# rack_lifecycle.sh run.
#
# WHY FULL LDAP DETACHMENT IS SAFE HERE (confirmed 2026-09-29, not a repeat
# of the §4.5 in-cluster regression): engineering-manual §4.5 documents a
# real, previously-hit regression where setting nsswitch.conf to files-only
# broke LOGIN FOR EVERY OTHER LDAP-AUTHENTICATED USER on a node that still
# needed LDAP for people other than cmsupport - that fix was reverted and
# explicitly marked "do not bake into the reference image." This script does
# NOT repeat that mistake, for two independent reasons:
#   1. cmsupport is created as a real local /etc/passwd/shadow/group entry
#      BEFORE nsswitch is changed (§4.5's own candidate fix #2), so it
#      resolves locally instead of hitting the same "no such user" failure.
#   2. More fundamentally: this fleet has no in-cluster LDAP dependency at
#      all - confirmed directly - so there is no "other user still needs
#      LDAP" case to break here in the first place. §4.5's regression only
#      applies to a node meant to stay LDAP-reachable for non-cmsupport
#      users; these nodes are never meant to be that, so full detachment at
#      finalize time is the correct design, not a risk being taken.
#
# SCOPE — what this covers vs. what it deliberately does NOT:
#
#   Covered (pure filesystem edits, safe at finalize time):
#     - Preserve cmsupport as a local account (UID/GID 1000)
#     - Disable nslcd from autostarting (LDAP client daemon)
#     - Strip pam_ldap.so from the PAM stacks
#     - Set nsswitch.conf to files-only for passwd/group/shadow
#     - Disable cuda-dcgm from autostarting
#
#   NOT covered, deliberately, and still needs a separate step:
#     - CMDaemon-level cuda-dcgm monitoring disable (head-node-side BCM
#       database state via cmsh - not a per-node file, doesn't belong here).
#     - Stopping live nvidia-persistenced/cuda-dcgm processes - no GPU driver
#       is loaded yet during finalize; that's a post-boot diag-workflow step
#       (pre-diag/post-diag), not part of handoff, and not merged here.
#     - The stale-DNS fix (rack_lifecycle.sh handoff step 1) - out of scope
#       per what was asked (LDAP + cuda-dcgm only). Same /localdisk pattern,
#       could be added the same way if wanted later.
#
# ROOT-CAUSE FINDING, 2026-09-29 - confirmed via reading rack_lifecycle.sh's
# actual handoff() source: the live script's step 2 (create local cmsupport)
# runs BEFORE step 3 (stop nslcd). At the moment `useradd` runs, LDAP is
# still active in NSS. The script's own check (`grep "^cmsupport:"
# /etc/passwd`) correctly finds no *local* entry - but `useradd` internally
# also does its own NSS lookup (getpwnam) to check for name collisions, and
# that lookup still resolves `cmsupport` via LDAP at that point. So `useradd`
# refuses with "already exists" - not because of a real local conflict, but
# because of a same-script step-ordering race against its own LDAP-disable
# step that runs after it. This is a genuine, previously-undiagnosed bug in
# rack_lifecycle.sh itself, not a fleet/environment issue.
#
# WHY MERGING INTO FINALIZE FIXES THIS, NOT JUST RELOCATES IT: at finalize
# time, the node hasn't booted into its LDAP-integrated state at all - there
# is no NSS/LDAP resolution happening in the node-installer ramdisk against
# the target's config. Writing the account directly into the target's
# /localdisk/etc/{passwd,shadow,group} files has nothing to collide with,
# because LDAP resolution for this node effectively never turns on before
# this script runs. The race condition doesn't just move earlier - it stops
# being possible.
#
# Replicates the live script's exact account parameters (UID/GID 1000,
# shell /bin/bash, comment "cmsupport (local, off-cluster)", home
# /home/cmsupport) rather than looking up values via getent, since there is
# no live LDAP resolution available in the finalize ramdisk to query.
#
# The nslcd "disable" uses a systemd mask (symlink to /dev/null) rather than
# replicating `systemctl disable nslcd` exactly, since the live systemctl
# call talks to a running systemd that doesn't exist yet in the finalize
# ramdisk. Standard chroot-free equivalent; worth confirming once against a
# real run.
#
# VALIDATION STATUS (2026-09-29, real rack08node04 re-provision test, after
# category-level `services; set monitored no; set autostart no` was also
# applied for cuda-dcgm/nslcd on maxQ-1032-doca341):
#   - cmsupport preservation: not yet specifically re-checked on this run.
#   - nslcd mask: CONFIRMED - masked, inactive, held after boot.
#   - cuda-dcgm: FAILED on this run - symlink-removal-only was not durable,
#     came back enabled+active within ~1min of boot (see step 5 below for
#     root cause and the mask-based fix now in place). Not yet re-tested
#     since the fix.
# Re-provision once more after this edit and re-check cuda-dcgm specifically
# before trusting it fleet-wide.
#
# Idempotent: safe to run again on a reinstall without duplicating edits.

ROOT="/localdisk"
PAM_DIR="${ROOT}/etc/pam.d"
NSSWITCH="${ROOT}/etc/nsswitch.conf"

CMSUPPORT_UID=1000
CMSUPPORT_GID=1000
CMSUPPORT_HOME="/home/cmsupport"
CMSUPPORT_SHELL="/bin/bash"
CMSUPPORT_GECOS="cmsupport (local, off-cluster)"

log_ldap() { echo "finalize-hosts-127-v4[${NODE_HOSTNAME}]: $*"; }

if [[ ! -d "$ROOT" ]]; then
  log_ldap "${ROOT} does not exist at this stage - skipping part 2 entirely" >&2
else

  # ---------------------------------------------------------------------------
  # 1. Preserve cmsupport as a local account (UID/GID 1000), by writing
  #    directly to /localdisk's passwd/shadow/group rather than running
  #    useradd, so there's no reliance on chroot or a live NSS stack.
  # ---------------------------------------------------------------------------
  PASSWD_FILE="${ROOT}/etc/passwd"
  SHADOW_FILE="${ROOT}/etc/shadow"
  GROUP_FILE="${ROOT}/etc/group"

  if [[ ! -f "$PASSWD_FILE" || ! -f "$SHADOW_FILE" || ! -f "$GROUP_FILE" ]]; then
    log_ldap "one or more of ${PASSWD_FILE}/${SHADOW_FILE}/${GROUP_FILE} missing - skipping cmsupport step"
  elif grep -q "^cmsupport:" "$PASSWD_FILE"; then
    log_ldap "cmsupport already present in ${PASSWD_FILE} - skipping"
  else
    if grep -qE "^[^:]+:[^:]*:${CMSUPPORT_GID}:" "$GROUP_FILE"; then
      log_ldap "GID ${CMSUPPORT_GID} already exists in ${GROUP_FILE} - reusing it"
    else
      echo "cmsupport:x:${CMSUPPORT_GID}:" >> "$GROUP_FILE"
      log_ldap "added group cmsupport (GID ${CMSUPPORT_GID}) to ${GROUP_FILE}"
    fi

    echo "cmsupport:x:${CMSUPPORT_UID}:${CMSUPPORT_GID}:${CMSUPPORT_GECOS}:${CMSUPPORT_HOME}:${CMSUPPORT_SHELL}" >> "$PASSWD_FILE"
    log_ldap "added cmsupport (UID ${CMSUPPORT_UID}) to ${PASSWD_FILE}"

    TODAY_DAYS=$(( $(date +%s) / 86400 ))
    echo "cmsupport:!:${TODAY_DAYS}:0:99999:7:::" >> "$SHADOW_FILE"
    log_ldap "added locked-password shadow entry for cmsupport to ${SHADOW_FILE}"

    HOME_DIR="${ROOT}${CMSUPPORT_HOME}"
    if [[ ! -d "$HOME_DIR" ]]; then
      mkdir -p "$HOME_DIR"
      chown "${CMSUPPORT_UID}:${CMSUPPORT_GID}" "$HOME_DIR"
      chmod 700 "$HOME_DIR"
      log_ldap "created home directory ${HOME_DIR}"
    else
      log_ldap "home directory ${HOME_DIR} already exists - leaving as-is"
    fi
  fi

  # ---------------------------------------------------------------------------
  # 2. Disable nslcd from autostarting (mask).
  # ---------------------------------------------------------------------------
  NSLCD_UNIT="${ROOT}/etc/systemd/system/nslcd.service"
  if [[ -L "$NSLCD_UNIT" ]] && [[ "$(readlink "$NSLCD_UNIT")" == "/dev/null" ]]; then
    log_ldap "nslcd already masked - skipping"
  else
    mkdir -p "$(dirname "$NSLCD_UNIT")"
    ln -sf /dev/null "$NSLCD_UNIT"
    log_ldap "masked nslcd.service"
  fi

  for wants_dir in "${ROOT}"/etc/systemd/system/*.wants; do
    [[ -d "$wants_dir" ]] || continue
    if [[ -L "${wants_dir}/nslcd.service" ]]; then
      rm -f "${wants_dir}/nslcd.service"
      log_ldap "removed nslcd.service enable-symlink from $(basename "$wants_dir")"
    fi
  done

  # ---------------------------------------------------------------------------
  # 2b. Disable nscd (mask, same technique that held for nslcd/cuda-dcgm) and
  #     clear any cached passwd/group/netgroup entries it already wrote.
  #
  #     Added 2026-09-29 per report: nsswitch.conf -> files only stops NEW
  #     lookups from going to LDAP, but does nothing about entries nscd
  #     already cached before handoff - those can keep resolving against
  #     stale LDAP-sourced UID/GID/group-membership data (e.g. for folder/
  #     mount permission checks) until the cache's own TTL expires (reported
  #     as ~15min), independent of the nsswitch change. Covers both common
  #     cache directory locations (RHEL-family /var/db/nscd, Debian-family
  #     /var/cache/nscd) since the image's actual distro base wasn't
  #     confirmed at the time of writing.
  # ---------------------------------------------------------------------------
  NSCD_UNIT="${ROOT}/etc/systemd/system/nscd.service"
  if [[ -L "$NSCD_UNIT" ]] && [[ "$(readlink "$NSCD_UNIT")" == "/dev/null" ]]; then
    log_ldap "nscd already masked - skipping"
  elif [[ -f "${ROOT}/usr/lib/systemd/system/nscd.service" || -f "${ROOT}/lib/systemd/system/nscd.service" ]]; then
    mkdir -p "$(dirname "$NSCD_UNIT")"
    ln -sf /dev/null "$NSCD_UNIT"
    log_ldap "masked nscd.service"
  else
    log_ldap "nscd.service unit not present on this image - skipping mask"
  fi

  for wants_dir in "${ROOT}"/etc/systemd/system/*.wants; do
    [[ -d "$wants_dir" ]] || continue
    if [[ -L "${wants_dir}/nscd.service" ]]; then
      rm -f "${wants_dir}/nscd.service"
      log_ldap "removed nscd.service enable-symlink from $(basename "$wants_dir")"
    fi
  done

  nscd_cache_cleared=0
  for nscd_cache_dir in "${ROOT}/var/db/nscd" "${ROOT}/var/cache/nscd"; do
    if [[ -d "$nscd_cache_dir" ]]; then
      rm -f "${nscd_cache_dir}"/passwd "${nscd_cache_dir}"/group "${nscd_cache_dir}"/netgroup "${nscd_cache_dir}"/services 2>/dev/null
      log_ldap "cleared cached passwd/group/netgroup entries from ${nscd_cache_dir}"
      nscd_cache_cleared=1
    fi
  done
  if [[ "$nscd_cache_cleared" -eq 0 ]]; then
    log_ldap "no nscd cache directory found - nothing to clear"
  fi

  # ---------------------------------------------------------------------------
  # 2c. Mask sssd (added 2026-09-29): this fleet's images resolve identity
  #     via either nslcd OR sssd depending on the image line (confirmed per
  #     engineering-manual §4.5 - the SSSD-hang investigation on a different
  #     category). Steps 2/2b only ever covered nslcd/nscd; if a node's PAM/
  #     NSS stack actually goes through SSSD, none of that masked anything,
  #     which is the likely cause of a reported ~15s SSH-login stall for
  #     cmsupport (NSS account lookup resolves fine locally via nsswitch, but
  #     PAM authentication still tries SSSD/LDAP first and times out before
  #     falling back to local Unix auth - two separate subsystems, one fix
  #     doesn't cover both). Mask unconditionally alongside nslcd/nscd so
  #     whichever backend a given image uses, it's covered.
  # ---------------------------------------------------------------------------
  SSSD_UNIT="${ROOT}/etc/systemd/system/sssd.service"
  if [[ -L "$SSSD_UNIT" ]] && [[ "$(readlink "$SSSD_UNIT")" == "/dev/null" ]]; then
    log_ldap "sssd already masked - skipping"
  elif [[ -f "${ROOT}/usr/lib/systemd/system/sssd.service" || -f "${ROOT}/lib/systemd/system/sssd.service" ]]; then
    mkdir -p "$(dirname "$SSSD_UNIT")"
    ln -sf /dev/null "$SSSD_UNIT"
    log_ldap "masked sssd.service"
  else
    log_ldap "sssd.service unit not present on this image - skipping mask"
  fi

  for wants_dir in "${ROOT}"/etc/systemd/system/*.wants; do
    [[ -d "$wants_dir" ]] || continue
    if [[ -L "${wants_dir}/sssd.service" ]]; then
      rm -f "${wants_dir}/sssd.service"
      log_ldap "removed sssd.service enable-symlink from $(basename "$wants_dir")"
    fi
  done

  for sssd_cache_dir in "${ROOT}/var/lib/sss/db" "${ROOT}/var/lib/sss/mc"; do
    if [[ -d "$sssd_cache_dir" ]]; then
      rm -f "${sssd_cache_dir}"/*.ldb "${sssd_cache_dir}"/passwd "${sssd_cache_dir}"/group "${sssd_cache_dir}"/initgroups 2>/dev/null
      log_ldap "cleared cached sssd entries from ${sssd_cache_dir}"
    fi
  done

  # ---------------------------------------------------------------------------
  # 3. Strip pam_ldap.so AND pam_sss.so from the PAM stacks.
  #
  # Originally only stripped pam_ldap.so. Added pam_sss.so 2026-09-29 for the
  # same reason as step 2c above - SSSD auth going untouched is the leading
  # explanation for a reported ~15s SSH-login stall on cmsupport even though
  # NSS account lookup (getent) already resolves it instantly. Both modules
  # stripped regardless of which one(s) are actually present.
  # ---------------------------------------------------------------------------
  for pam_file in common-account common-auth common-session common-password; do
    f="${PAM_DIR}/${pam_file}"
    if [[ ! -f "$f" ]]; then
      log_ldap "${f} not present - skipping"
      continue
    fi
    removed_any=0
    if grep -q "pam_ldap.so" "$f"; then
      sed -i '/pam_ldap\.so/d' "$f"
      log_ldap "removed pam_ldap.so from ${pam_file}"
      removed_any=1
    fi
    if grep -q "pam_sss.so" "$f"; then
      sed -i '/pam_sss\.so/d' "$f"
      log_ldap "removed pam_sss.so from ${pam_file}"
      removed_any=1
    fi
    if [[ "$removed_any" -eq 0 ]]; then
      log_ldap "pam_ldap.so/pam_sss.so already absent from ${pam_file} - skipping"
    fi
  done

  # ---------------------------------------------------------------------------
  # 4. nsswitch.conf to files-only for passwd/group/shadow.
  #
  # Changed 2026-09-29 to unconditionally rewrite each line (matching
  # rack_lifecycle.sh's own live approach) rather than only rewriting when the
  # literal word "ldap" was detected first. The old conditional missed any
  # line whose backend was "sss" instead of "ldap" (SSSD-based images) -
  # those lines were silently left untouched while the script logged
  # "already files-only", which is the same root cause as steps 2c/3 above.
  # Unconditional rewrite is still idempotent - running it again when the
  # line already reads "files" is a no-op.
  # ---------------------------------------------------------------------------
  if [[ -f "$NSSWITCH" ]]; then
    for db in passwd group shadow; do
      if grep -qE "^${db}:\s*files\s*\$" "$NSSWITCH"; then
        log_ldap "${db} already files-only in nsswitch.conf - skipping"
      else
        sed -i -E "s/^(${db}:\s*).*/\1files/" "$NSSWITCH"
        log_ldap "set ${db} to files-only in nsswitch.conf"
      fi
    done
  else
    log_ldap "${NSSWITCH} not present - skipping"
  fi

  # ---------------------------------------------------------------------------
  # 5. Disable cuda-dcgm from autostarting.
  #
  # CONFIRMED 2026-09-29 (real rack08node04 re-provision test): removing only
  # the multi-user.target.wants enable-symlink is NOT sufficient - it came
  # back (symlink recreated, service active) within ~1min of boot, while
  # nslcd's mask (below and in step 2) held. Root cause: cuda-dcgm.service
  # reports `preset: enabled`, and something at first real boot (systemd
  # preset re-application is the leading suspect) re-enables any unit that
  # was merely "disabled" via symlink removal - but `systemctl enable`/preset
  # explicitly refuse to touch a MASKED unit. Masking, not symlink removal,
  # is what actually survived on nslcd, so cuda-dcgm now gets the same
  # treatment: mask the real unit file directly (ln -sf /dev/null over the
  # /usr/lib/systemd/system/cuda-dcgm.service path itself), same pattern
  # `systemctl mask` uses to make a unit immune to enable/preset.
  # ---------------------------------------------------------------------------
  DCGM_UNIT_REAL="${ROOT}/usr/lib/systemd/system/cuda-dcgm.service"
  DCGM_UNIT_MASK="${ROOT}/etc/systemd/system/cuda-dcgm.service"
  DCGM_LINK="${ROOT}/etc/systemd/system/multi-user.target.wants/cuda-dcgm.service"

  # Remove the wants-symlink too (belt and suspenders - harmless either way).
  if [[ -L "$DCGM_LINK" ]]; then
    rm -f "$DCGM_LINK"
    log_ldap "removed cuda-dcgm.service enable-symlink from multi-user.target.wants"
  fi

  if [[ -L "$DCGM_UNIT_MASK" ]] && [[ "$(readlink "$DCGM_UNIT_MASK")" == "/dev/null" ]]; then
    log_ldap "cuda-dcgm already masked - skipping"
  elif [[ ! -f "$DCGM_UNIT_REAL" ]]; then
    log_ldap "WARNING: ${DCGM_UNIT_REAL} not found - skipping cuda-dcgm mask, needs manual check"
  else
    mkdir -p "$(dirname "$DCGM_UNIT_MASK")"
    ln -sf /dev/null "$DCGM_UNIT_MASK"
    log_ldap "masked cuda-dcgm.service (${DCGM_UNIT_MASK} -> /dev/null)"
  fi

  log_ldap "part 2 done. NOTE: CMDaemon-level cuda-dcgm monitoring disable (head-node-side) is NOT covered by this script - see header comment."
fi

log_hosts "finalize-hosts-127-v4 complete (parts 1 and 2)."
